### ISSUE TITLE
running errors: GLSL 4.30 is not supported.

### ISSUE THREAD

**Issue by shuwang1** [MauriceGit/Partikel_accelleration_on_GPU#10]
When running the codes, it showed the errors

```
Status: Using GLEW 1.13.0
--> Shader laden...
Compiling Vertex shader
vertexShaderErrorMessage: 0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Compiling Fragment shader
fragmentShaderErrorMessage: 0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

programErrorMessage: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Compiling Compute shader
computeShaderErrorMessage: 0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
0:0(0): error: Compute shaders require GLSL 4.30 or GLSL ES 3.10
```

Then, I checked my computer with glxinfo and it shows

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (CHV)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 20.2.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

It seems that my computer supports 4.6 Core profile.   How do I know if my computer supports GLSL 4.30 or not? Thank you!

**Comment by MauriceGit** [comment]
The issue seems to be, that I don't explicitly ask for an OpenGL core version 4.3, but pretty much any version (which should default to the highest available normally). In your case, it seems like it returns a compatibility context instead. And your non-core OpenGL context seems to only support GLSL in version 1.3 (line "OpenGL shading language version string: 1.30").

That should easily be fixed by requiring the actual OpenGL core context. 

I tried that, but get an invalid window handle, so there is another issue somewhere (probably in my code somewhere).

What you could try is: 
- Comment the line 230 in file io.c ("glfwDefaultWindowHints()") 
- Add the following lines instead at the same position:glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

See, if it runs like that. If it segfaults, we have the same issue and I'll see, if I can fix it..

**Comment by shuwang1** [comment]
Thank you! A great job!  I guess it is my hardware is too outdated.

Cheers
